import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
  buttonContainer: {
    position: 'absolute',
    top: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  iconButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 30,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  faceGuideContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  faceGuide: {
    width: 250,
    height: 300,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 150,
    borderStyle: 'dashed',
  },
  countdownContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 100,
    height: 100,
    marginLeft: -50,
    marginTop: -50,
    borderRadius: 50,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  countdownText: {
    fontSize: 48,
    fontWeight: 'bold',
    color: 'white',
    includeFontPadding: false,
    lineHeight: 48,
  },
  idInputContainer: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    zIndex: 1000,
  },
  idInputLabel: {
    marginBottom: 10,
    fontSize: 16,
    color: 'white',
  },
  idInput: {
    backgroundColor: 'white',
    borderRadius: 5,
    width: '100%',
    height: 40,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  idSubmitButton: {
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
    width: '100%',
    alignItems: 'center',
  },
  idSubmitButtonText: {
    color: '#000000',
    fontWeight: 'bold',
    fontSize: 16,
  },
  idCancelButton: {
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
    width: '100%',
    alignItems: 'center',
    marginTop: 10,
  },
  idCancelButtonText: {
    color: '#aaaaaa',
  },
  processingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  processingText: {
    marginTop: 10,
    color: 'white',
    fontSize: 16,
  },
  statusContainer: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRadius: 10,
    padding: 10,
    zIndex: 900,
  },
  statusText: {
    color: 'white',
    marginBottom: 5,
  },
  captureButton: {
    marginTop: 10,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
  },
  captureButtonText: {
    color: '#000000',
    fontWeight: 'bold',
    fontSize: 16,
  },
  successMessageContainer: {
    position: 'absolute',
    top: 40,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(46, 125, 50, 0.85)',
    borderRadius: 10,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 999,
  },
  successMessageContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  messageTextContainer: {
    marginLeft: 10,
    flex: 1,
  },
  successMessageTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 5,
  },
  successMessageText: {
    fontSize: 14,
    color: 'white',
    marginBottom: 2,
  },
  errorMessageContainer: {
    position: 'absolute',
    top: 40,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(183, 28, 28, 0.85)',
    borderRadius: 10,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    zIndex: 999,
  },
  errorMessageContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  errorMessageTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 5,
  },
  errorMessageText: {
    fontSize: 14,
    color: 'white',
    marginBottom: 2,
  },
});
