import {
    FromToDateColumns,
    HeaderTransactionsColumn,
    HeaderGenerallistColumn,
    HeaderNamePrimaryColumn,
    TransactionsDetailsColumns,
    AuditTransactionColumns,
    nameTransaction,
    hideWhenColumnEmployeeMonthlyAttendance,
    noteColumn,
} from './columnHelpers';
import { IconCalendarSmall, IconCheckOut, IconTimeManagement, IconTimeStart, IconTimeStop } from '../assets/IconsSvg';
import { getStatusColor } from '../components/Schedule/shiftPalette';
import StatusList from './StatusList';

export const DataPages = {
    VacationTransaction: {
        Api: 'VacationTransaction',
        keyId: 'recId',
        ErrorsKeys: {
            key1: "employeeRecFullName",
            key2: "personalNumber",
        },
        gridList: {
            employeeRecGender: "Gender",
            status: "WorkflowStatus",
        },
        columns: [
            ...HeaderTransactionsColumn(),
            ...FromToDateColumns(),
            {
                key: "balance",
                title: "balance",
                type: "number",
                import: false,
                rowGroup: "balanceNumbers",
                backgroundRowGroup: "background",
                cellWidth: '31%',
            },
            {
                key: "duration",
                title: "duration",
                type: "number",
                import: false,
                rowGroup: "balanceNumbers",
                cellWidth: '31%',
            },
            {
                key: "remainder",
                title: "remainder",
                type: "number",
                import: false,
                rowGroup: "balanceNumbers",
                cellWidth: '31%',
            },
            ...TransactionsDetailsColumns(),
            nameTransaction(),

            ...AuditTransactionColumns(),

        ],
    },
    AttendanceException: {
        Api: 'AttendanceException',
        keyId: 'recId',
        gridList: {
            timing: 'AttendanceExceptionTiming',
            status: 'WorkflowStatus',
        },
        columns: [
            ...HeaderTransactionsColumn({
                codeKey: 'attendanceExceptionSetupCode',
                key: 'attendanceExceptionSetupName',
                keyRecId: 'attendanceExceptionSetupRecId',
                lookupName: 'AttendanceExceptionSetup',
                ResourcePage: 'AttendanceExceptionSetup',
            }),
            ...FromToDateColumns(),
            {
                key: 'timingName',
                title: 'title',
                generallist: 'AttendanceExceptionTiming',
                sendKey: 'timing',
            },
            nameTransaction(),

            ...TransactionsDetailsColumns(),
            ...AuditTransactionColumns(),
        ],
    },
    Mission: {
        Api: 'Mission',
        keyId: 'recId',
        gridList: {
            status: "WorkflowStatus",
            type: "MissionSubTypes",
            isFullDay: "NoYes",
        },
        columns: [
            ...HeaderGenerallistColumn({
                key: "typeName",
                generallist: "MissionSubTypes",
            }),
            {
                key: "isFullDayName",
                title: "isFullDayMission",
                generallist: "NoYes",
                StatusList: StatusList.NoYes,
                isFilter: true,
                type: "status",
                secondKey: "isFullDay",
            },
            {
                key: "reasonName",
                title: "title",
                lookupName: "Reason",
                ResourcePage: "Reason",
                keyRecId: "reasonRecId",
                codeKey: "reasonCode",
                ModalContent: true,
                isFilter: true,
            },
            ...FromToDateColumns({ fromKey: 'dateTimeFrom', toKey: 'dateTimeTo', type: 'dateTime' }),

            {
                key: "locationName",
                title: "title",
                lookupName: "Location",
                ResourcePage: "Location",
                codeKey: "locationCode",
                keyRecId: "locationRecId",
                ModalContent: true,
                isFilter: true,
            },
            nameTransaction(),
            ...TransactionsDetailsColumns(),
            ...AuditTransactionColumns(),
        ],
    },
    MissedAttendanceRequest: {
        Api: 'MissedAttendanceRequest',
        keyId: 'recId',
        gridList: {
            status: "WorkflowStatus",
            forgetFinger: "ForgetFinger",
        },
        columns: [
            ...HeaderGenerallistColumn({
                key: "forgetFingerName",
                generallist: "ForgetFinger",
            }),
            {
                key: "attendanceDateIn",
                title: "checkIn",
                ResourcePage: "GeneralField",
                type: "date",
                rowGroup: "shift",
                checkedViwe: {
                    key: "forgetFinger",
                    value: [1, 3]
                },
                cellWidth: '48%',
                isFilter: true,
                ModalContent: true,
            },
            {
                key: "timeIn",
                title: "timeIn",
                ResourcePage: "GeneralField",
                type: "time",
                rowGroup: "shift",
                format: "onlyHours",
                checkedViwe: {
                    key: "forgetFinger",
                    value: [1, 3]
                },
                cellWidth: '48%',
                isFilter: true,
                ModalContent: true,
            },
            {
                key: "attendanceDateOut",
                title: "checkOut",
                ResourcePage: "GeneralField",
                rowGroup: "shift",
                checkedViwe: {
                    key: "forgetFinger",
                    value: [2, 3]
                },
                cellWidth: '48%',
                type: "date",
                isFilter: true,
                ModalContent: true,
            },
            {
                key: "timeOut",
                title: "timeOut",
                ResourcePage: "GeneralField",
                type: "time",
                format: "onlyHours",
                checkedViwe: {
                    key: "forgetFinger",
                    value: [2, 3]
                },
                rowGroup: "shift",
                cellWidth: '48%',
                isFilter: true,
                ModalContent: true,
            },
            nameTransaction(),
            ...TransactionsDetailsColumns(),
            ...AuditTransactionColumns(),
        ],
    },
    PartialDayLeave: {
        Api: 'PartialDayLeave',
        keyId: 'recId',
        gridList: {
            status: "WorkflowStatus",
            isDeduction: "NoYes",
        },
        columns: [
            ...HeaderTransactionsColumn({
                key: "attendanceSetupName",
                codeKey: "attendanceSetupCode",
                lookupName: "AttendanceSetup/GetCustomLookupAsync?type=8",
                keyGetLookup: false,
                keyRecId: "attendanceSetupRecId",
                ResourcePage: "AttendanceSetupPartialDayLeave",
            }),
            {
                key: "isDeductionName",
                title: "isDeduction",
                generallist: "NoYes",
                StatusList: StatusList.NoYes,
                secondKey: "isDeduction",
                type: "status",
                ModalContent: true,
                isFilter: true,
                import: false,
            },
            {
                key: "reasonName",
                title: "title",
                codeKey: "reasonCode",
                lookupName: "Reason",
                ResourcePage: "Reason",
                keyRecId: "reasonRecId",
                ModalContent: true,
                isFilter: true,
                import: true,
            },

            {
                key: "totalCountPerMonth",
                title: "totalCountPerMonth",
                type: "number",
                ResourcePage: "PartialDayLeave",
                ModalContent: true,
                isFilter: true,
                import: false,
                rowGroup: "monthlyTotals",
            },
            {
                key: "totalPeriodPerMonth",
                title: "totalPeriodPerMonth",
                type: "number",
                ResourcePage: "PartialDayLeave",
                ModalContent: true,
                isFilter: true,
                import: false,
                rowGroup: "monthlyTotals",
            },
            ...FromToDateColumns({ fromKey: 'dateTimeFrom', toKey: 'dateTimeTo', type: 'dateTime' }),

            nameTransaction(),
            ...TransactionsDetailsColumns({ keyTrans: "transactionDate" }),
            ...AuditTransactionColumns(),
        ],
    },
    Payslip: {
        Api: 'EmployeeSelfServiceDashboard/GetEmployeePayrollList?employeeRecId',
        keyId: 'payrollEmployeeId',
        gridList: {
            employeeContractType: "PayrollEmployeeContractType",
        },
        columns: [
            {
                key: "monthYear",
                title: "monthYear",
                ResourcePage: "Payslip",
                secondKeyText: "code",
                fixed: true,
                ModalContent: true,
                cantHide: true,
                isHideTitleCard: true,
                isHeaderMobile: true,
                isCellAvatar: true,
                isCellAvatarText: false,
            },
            {
                key: "employeeContractTypeName",
                title: "title",
                generallist: "PayrollEmployeeContractType",
                secondKey: "employeeContractType",
                type: "status",
                isFilter: true,
                fixed: true,
                isHeaderMobile: true,
                isHideTitleCard: true,
                isRouteAddEdit: false,
                ImportExcel: true,
            },

            {
                key: "netSalary",
                title: "netSalary",
                type: "salary",
                currencyKey: "currencySymbol",
                ResourcePage: "GeneralField",
                import: false,
                rowGroup: "salaryBreakdown",
                cellWidth: '31%',
            },
            {
                key: "totalAllowances",
                title: "Allowances",
                ResourcePage: "GeneralField",
                type: "salary",
                currencyKey: "currencySymbol",
                import: false,
                color: "success",
                rowGroup: "salaryBreakdown",
                cellWidth: '31%',
            },
            {
                key: "totalDeductions",
                title: "Deductions",
                ResourcePage: "GeneralField",
                type: "salary",
                currencyKey: "currencySymbol",
                color: "error",
                import: false,
                rowGroup: "salaryBreakdown",
                cellWidth: '31%',
            },
            {
                key: "payrollName",
                title: "payrollName",
                ResourcePage: "Payslip",
                fixed: true,
                ModalContent: true,
                isFilter: true,
            },
            {
                key: "executionDate",
                title: "executionDate",
                ResourcePage: "GeneralTransaction",
                type: "date",
                isFilter: true,
            },
        ],
    },
    EmployeeMonthlyAttendanceSelfservice: {
        Api: 'DailyAttendance/EmployeeMonthlyAttendance',
        keyId: 'attendanceDate',
        gridList: {
            hasVacation: "NoYes",
            hasException: "NoYes",
            hasMission: "NoYes",
            hasPartialLeave: "NoYes",

            dayStatus: "CalenderDayStatus"
        },
        columns: [
            {
                key: "attendanceDate",
                isHeaderMobile: true,
                isHideTitleCard: true,
                title: "day",
                ResourcePage: "GeneralField",
                type: "dateAndDay",
                isFilter: true,
            },
            {
                key: "dayStatusName",
                title: "dayStatusName",
                secondKey: "dayStatus",
                isHeaderMobile: true,
                isHideTitleCard: true,
                type: "status",
                generallist: "CalenderDayStatus",
                isFilter: true,
            },

            {
                key: "effectiveShiftStart",
                title: "shiftStart",
                ResourcePage: "GeneralField",
                type: "timeWithIcon",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,

                format: "onlyHours",
                icon: IconTimeStart,
                rowGroup: "shift",
                cellWidth: '31%',
                isFilter: true,
            },
            {
                key: "effectiveShiftEnd",
                title: "shiftEnd",
                type: "timeWithIcon",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,

                format: "onlyHours",
                icon: IconTimeStop,
                ResourcePage: "GeneralField",
                rowGroup: "shift",
                cellWidth: '31%',
                isFilter: true,
            },
            {
                key: "workingDuration",
                title: "title",
                ResourcePage: "Shift",
                format: "hours",
                type: "timeWithIcon",
                icon: IconCalendarSmall,
                rowGroup: "shift",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,

                cellWidth: '31%',
                isFilter: true,
            },
            {
                key: "timeIn",
                title: "checkIn",
                ResourcePage: "Dashboard",
                type: "timeWithIcon",
                icon: IconCheckOut,
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                format: "time",
                iconRotate: true,
                ModalContent: true,
                rowGroup: "time",
                cellWidth: '31%',
                isFilter: true,
            },
            {
                key: "timeOut",
                title: "checkOut",
                ResourcePage: "Dashboard",
                type: "timeWithIcon",
                format: "time",
                icon: IconCheckOut,
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                ModalContent: true,
                rowGroup: "time",
                cellWidth: '31%',
                isFilter: true,
            },
            {
                key: "actualWorking",
                title: "actualWorking",
                ResourcePage: "GeneralField",
                format: "hours",
                type: "timeWithIcon",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,

                icon: IconTimeManagement,
                rowGroup: "time",
                cellWidth: '31%',
                color: "primary",
                isFilter: true,
            },

            {
                key: "earlyComeAfterSegmentation",
                title: "earlyCome",
                ResourcePage: "GeneralField",
                type: "hours",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                cellWidth: '31%',

                rowGroup: "Segmentation",
                ModalContent: true,
                isFilter: true,
            },

            {
                key: "earlyLeaveAfterSegmentation",
                title: "earlyLeave",
                ResourcePage: "GeneralField",
                type: "hours",
                cellWidth: '31%',

                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                rowGroup: "Segmentation",
                ModalContent: true,
                isFilter: true,
            },

            {
                key: "lateComeAfterSegmentation",
                title: "lateCome",
                ResourcePage: "GeneralField",
                type: "hours",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                cellWidth: '31%',

                rowGroup: "Segmentation",
                ModalContent: true,
                isFilter: true,
            },

            {
                key: "lateLeaveAfterSegmentation",
                title: "lateLeave",
                ResourcePage: "GeneralField",
                type: "hours",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                cellWidth: '31%',

                rowGroup: "Segmentation",
                ModalContent: true,
                isFilter: true,
            },
            {
                key: "totalOvertimeAfterSegmentation",
                title: "totalOvertime",
                ResourcePage: "GeneralField",
                type: "hours",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                cellWidth: '31%',

                rowGroup: "Segmentation",
                ModalContent: true,
                isFilter: true,
            },
            {
                key: "status",
                title: "satuts",
                ResourcePage: "GeneralField",
                type: "switchStatus",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                switch: [
                    {
                        key: "isAbsent",
                        chackedKey: 2,
                        ResourcePage: "General",
                        title: "abcence",
                        color: "error",
                    },
                    {
                        key: "isAbsent",
                        chackedKey: 1,
                        ResourcePage: "General",
                        title: "Present",
                        color: "success",
                    },
                    {
                        key: "hasVacation",
                        chackedKey: 2,
                        ResourcePage: "General",
                        title: "Present",
                        color: "info",
                    }
                ],
                isFooter: true,
            },

            {
                key: "hasPartialLeave",
                title: "title",
                ResourcePage: "PartialDayLeave",
                CheckedValue: 2,
                type: "statusChecked",
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                color: getStatusColor('partialLeave'),
                isFooter: true,
                ModalContent: true,
                isFilter: true,
            },
            {
                key: "hasMission",
                title: "title",
                ResourcePage: "Mission",
                type: "statusChecked",
                CheckedValue: 2,
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                color: getStatusColor('mission'),
                isFooter: true,
                ModalContent: true,
                isFilter: true,
            },
            {
                key: "hasException",
                title: "title",
                ResourcePage: "AttendanceException",
                type: "statusChecked",
                CheckedValue: 2,
                hideWhen: hideWhenColumnEmployeeMonthlyAttendance,
                isFooter: true,
                ModalContent: true,
                isFilter: true,
            }

        ],
    },
    EmployeeBank: {
        Api: 'EmployeeBank',
        keyId: 'recId',
        isPrimaryActive: true,
        gridList: {
            idNumberType: 'EmployeeIdNumberType',
            isPrimary: 'NoYes',
        },
        columns: [
            ...HeaderNamePrimaryColumn({ nameKey: 'bankName', nameResourcePage: 'Bank', StatusList: StatusList.NoYes }),

            {
                key: 'bankBranchName',
                lookupName: 'BankBranch',
                title: 'title',
                ResourcePage: 'BankBranch',
                codeKey: 'bankBranchCode',
                keySendToImport: 'bankBranchCode',

                fixed: true,
                isFilter: true,
                ModalContent: true,
                isRequired: true,
            },
            {
                key: 'bankAccount',
                title: 'bankAccount',
                ResourcePage: 'GeneralField',

                isFilter: true,
                isRequired: true,
            },
            {
                key: 'giro',
                title: 'giro',
                ResourcePage: 'GeneralField',

                isFilter: true,
            },
            {
                key: 'iban',
                title: 'iban',
                ResourcePage: 'GeneralField',

                isFilter: true,
            },
            {
                key: 'bankingID',
                title: 'bankingID',
                ResourcePage: 'GeneralField',

                isFilter: true,
            },
            noteColumn,
        ],
    },
    EmployeeAddress: {
        Api: 'EmployeeAddress',
        keyId: 'recId',
        isPrimaryActive: true,
        gridList: {
            isPrimary: 'NoYes',
        },
        columns: [
            ...HeaderNamePrimaryColumn({ StatusList: StatusList.NoYes }),
            {
                key: 'addressTypeName',
                keyRecId: 'addressTypeRecId',
                lookupName: 'AddressType',
                codeKey: 'addressTypeCode',
                title: 'title',
                ResourcePage: 'AddressType',

                fixed: true,
                isFilter: true,
            },

            {
                key: 'countryName',
                keyRecId: 'countryRecId',
                lookupName: 'Country',
                codeKey: 'countryCode',
                title: 'title',
                ResourcePage: 'Country',

                isFilter: true,
            },
            {
                key: 'governorateName',
                lookupName: 'Governorate',
                codeKey: 'governorateCode',
                title: 'title',
                ResourcePage: 'Governorate',

                isFilter: true,
            },
            {
                key: 'cityName',
                lookupName: 'City',
                title: 'title',
                codeKey: 'cityCode',
                ResourcePage: 'City',

                isFilter: true,
            },
            {
                key: 'street',
                title: 'street',
                ResourcePage: 'GeneralField',

                isFilter: true,
            },
            {
                key: 'zipOrPostalCode',
                title: 'zipCode',
                ResourcePage: 'GeneralField',
                isFilter: true,
            },
        ],
    },
    BenefitEnrollmentRequest: {
        Api: 'BenefitEnrollmentRequest',
        keyId: 'recId',
        gridList: {
            status: "WorkflowStatus",
            useSegments: "NoYes",
            showInPaySlip: "NoYes",
            startingMonth: "Months",
            benefitCategory: "BenefitCategory",
            paySlipMonth: "Months",
        },
        columns: [
            ...HeaderTransactionsColumn({
                key: 'benefitPlanName',
                lookupName: 'BenefitPlan',
                ResourcePage: 'BenefitPlan',
            }),
            {
                key: "benefitCategoryName",
                title: "title",
                generallist: "BenefitCategoryMulti",
                sendKey: "benefitCategory",
                isRouteAddEdit: false,
                import: false,
            },
            {
                key: "enrollmentDate",
                title: "enrollmentDate",
                ResourcePage: "GeneralField",
                isRequired: true,
                ModalContent: true,
                type: "date",
                isFilter: true,
            },
            {
                key: "numberOfInstallments",
                title: "installmentNumber",
                type: "number",
                ResourcePage: "GeneralField",
                ModalContent: true,
                rowGroup: "install",

                isFilter: true,
                import: false,
            },
            {
                key: "amount",
                title: "amount",
                ResourcePage: "GeneralField",
                type: "salary",
                rowGroup: "install",
                currencyKey: "currencysymbol",
                import: false,
            },
            {
                key: "startingMonthName",
                title: "title",
                generallist: "Months",
                sendKey: "startingMonth",
                secondKey: "startingMonth",
                isFilter: true,
                isRouteAddEdit: false,
            },
            {
                key: "startYear",
                title: "year",
                type: "number",
                ResourcePage: "GeneralField",

                ModalContent: true,
                isFilter: true,
            },

            {
                key: "paySlipMonthName",
                title: "paySlipMonth",
                generallist: "Months",
                sendKey: "paySlipMonth",
                secondKey: "paySlipMonth",
                isRouteAddEdit: false,
            },
            {
                key: "paySlipYear",
                title: "paySlipYear",
                type: "number",
                ResourcePage: "GeneralField",
                ModalContent: true,
                isFilter: true,
            },
            {
                key: "defaultDisbursementPaymentTemplateName",
                title: "DefaultDisbursementPaymentTemplate",
                ResourcePage: "BenefitEnrollmentRequest",
                keyRecId: "defaultDisbursementPaymentTemplateRecId",
                lookupName: "PaymentTemplate",
                codeKey: "defaultDisbursementPaymentTemplateCode",
                ModalContent: true,
                isRouteAddEdit: false,
                isFilter: true,
            },
            {
                key: "paymentTemplateName",
                title: "title",
                ResourcePage: "PaymentTemplate",
                lookupName: "PaymentTemplate",
                keyRecId: "paymentTemplateRecId",
                codeKey: "paymentTemplateCode",
                ModalContent: true,
                isFilter: true,
            },

            nameTransaction({ ResourcePage: "BenefitEnrollmentRequest" }),
            ...TransactionsDetailsColumns(),
            ...AuditTransactionColumns(),
        ],
    },
}

export const DataPagesLine = {
    BenefitEnrollmentRequestEmployeePayment: {
        Api: 'BenefitEnrollmentRequestEmployeePayment',
        KeyGrid: "BenefitEnrollmentRequestPayment",
        keyId: 'recId',
        gridList: {
            month: "Months",
            isPaid: "NoYes",
        },
        columns: [
            {
                key: "name",
                title: "name",
                secondKeyText: "code",
                fixed: true,
                ModalContent: true,
                cantHide: true,
                isHideTitleCard: true,
                isHeaderMobile: true,
                isCellAvatar: true,
                isCellAvatarText: false,
            },
            {
                key: "isPaidName",
                generallist: "NoYes",
                secondKey: "isPaid",
                StatusList: StatusList.isPaid,
                overRideTitleList: {
                    2: {
                        "title": "isPaid",
                    },
                    1: {
                        "title": "notPaid",
                    }
                },
                type: "status",
                isFilter: true,
                fixed: true,
                isHeaderMobile: true,
                isHideTitleCard: true,
                isRouteAddEdit: false,
                ImportExcel: true,
            },

            {
                key: "amount",
                title: "amount",
                type: "salary",
                currencyKey: "currencySymbol",
                ResourcePage: "GeneralField",
                import: false,
                rowGroup: "balanceNumbers",
                backgroundRowGroup: "background",
                cellWidth: '40%',
            },
            {
                key: "monthName",
                title: "title",
                generallist: "Months",
                import: false,
                rowGroup: "balanceNumbers",
                cellWidth: '30%',
            },
            {
                key: "year",
                title: "year",
                ResourcePage: "GeneralField",
                import: false,
                rowGroup: "balanceNumbers",
                cellWidth: '20%',
            },


        ],
    },
}
